[package]
name = "rescrobbled"
version = "0.5.2+use.rustfm.scrobble.fork"
authors = ["Koen Bolhuis <koen.bolhuis@gmail.com>"]
edition = "2018"
license = "GPL-3.0"
repository = "https://github.com/InputUsername/rescrobbled.git"
homepage = "https://github.com/InputUsername/rescrobbled"
readme = "README.md"
description = "MPRIS music scrobbler daemon"
keywords = ["mpris", "music", "scrobble", "daemon"]
categories = ["multimedia", "command-line-utilities"]
publish = false

[dependencies]
mpris = "2.0.0-rc2"
rustfm-scrobble = { git = "https://github.com/InputUsername/rustfm-scrobble.git", branch = "use-attohttpc" }
listenbrainz = "0.4.1"
serde = { version = "1.0.136", features = ["derive"] }
toml = "0.5.8"
dirs = "4.0.0"
notify-rust = "4.5.6"
anyhow = "1.0.55"

[dev-dependencies]
tempfile = "3.3.0"
